const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { exec } = require('child_process');

// 📍 Paths relative to the ROOT of the project
const CONFIG_FILE = path.join(__dirname, '.playground-config.json');
const PLAYGROUND_FILE = path.join(__dirname, 'backend', 'src', 'prisma-playground.ts');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

// 🛡️ THE SAFE, READ-ONLY DIAGNOSTIC SCRIPT (Targeted for backend/src/)
const SAFE_PLAYGROUND_CODE = `// ⚠️ SAFE DIAGNOSTIC SCRIPT
// This file is auto-generated by the root-level playground-cli.js to prevent accidental destructive database operations.
import { PrismaClient } from './generated/prisma';

const prisma = new PrismaClient();

async function runDiagnostics() {
  console.log('\\n🔍 =========================================');
  console.log('🔍 RUNNING SAFE DATABASE DIAGNOSTICS...');
  console.log('🔍 =========================================\\n');

  try {
    const roles = await prisma.role.findMany({ include: { _count: { select: { rolePermissions: true } } } });
    console.log(\`👑 ROLES FOUND: \${roles.length}\`);
    roles.forEach(r => console.log(\`   - \${r.roleName} (ID: \${r.roleId}, Permissions: \${r._count.rolePermissions})\`));

    const properties = await prisma.property.findMany({ select: { propertyId: true, propertyName: true, subscriptionStatus: true, subscriptionEndsAt: true, trialEndsAt: true } });
    console.log(\`\\n🏨 PROPERTIES FOUND: \${properties.length}\`);
    properties.forEach(p => {
      const endDate = p.subscriptionEndsAt || p.trialEndsAt || 'N/A';
      console.log(\`   - [\${p.propertyId}] \${p.propertyName} | Status: \${p.subscriptionStatus} | Ends: \${endDate}\`);
    });

    const users = await prisma.user.findMany({ include: { role: { select: { roleName: true } }, property: { select: { propertyName: true } } } });
    console.log(\`\\n👤 USERS FOUND: \${users.length}\`);
    users.forEach(u => console.log(\`   - \${u.fullName} (\${u.username}) | Role: \${u.role?.roleName} | Hotel: \${u.property?.propertyName}\`));

    const roomTypes = await prisma.roomType.findMany({ include: { amenities: { include: { amenity: true } } } });
    console.log(\`\\n🛏️  ROOM TYPES FOUND: \${roomTypes.length}\`);
    roomTypes.forEach(rt => {
      const amenityNames = rt.amenities.map(a => a.amenity.name).join(', ') || 'None';
      console.log(\`   - [\${rt.roomTypeId}] \${rt.typeName} (GH₵\${rt.basePrice}) | Amenities: [\${amenityNames}]\`);
    });

  } catch (error: any) {
    console.error('❌ DATABASE ERROR:', error.message);
  } finally {
    await prisma.\$disconnect();
    console.log('\\n🔍 =========================================');
    console.log('🔍 DIAGNOSTICS COMPLETE. Copy the output above!');
    console.log('🔍 =========================================\\n');
  }
}

runDiagnostics();
`;

async function ensureConfig() {
  if (!fs.existsSync(CONFIG_FILE)) {
    console.log('\n⚙️  First time setup! Let\'s configure your playground.');
    const defaultCmd = 'cd backend && npx ts-node --transpile-only src/prisma-playground.ts';
    const cmd = await question(`Enter the command to run your prisma playground\n(Default: ${defaultCmd}):\n> `);
    
    const finalCmd = cmd.trim() || defaultCmd;
    const config = { command: finalCmd };
    
    fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));
    console.log('✅ Configuration saved to .playground-config.json');

    if (!fs.existsSync(PLAYGROUND_FILE)) {
      fs.writeFileSync(PLAYGROUND_FILE, SAFE_PLAYGROUND_CODE);
      console.log('✅ Safe prisma-playground.ts generated in backend/src/');
    }
  }
}

async function runPlayground() {
  await ensureConfig();
  const config = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
  
  console.log(`\n🚀 Running: ${config.command}\n`);
  console.log('---------------------------------------------------');
  
  // Execute in the root directory, allowing the command itself to handle 'cd backend' if needed
  exec(config.command, { cwd: __dirname }, (error, stdout, stderr) => {
    if (stdout) console.log(stdout);
    if (stderr) console.error(stderr);
    if (error) {
      console.error(`\n❌ Execution failed with code ${error.code}`);
    }
    console.log('---------------------------------------------------');
    rl.close();
  });
}

async function configure() {
  console.log('\n⚙️  Configure Playground Settings');
  const defaultCmd = 'cd backend && npx ts-node --transpile-only src/prisma-playground.ts';
  const cmd = await question(`Enter the command to run your prisma playground\n(Default: ${defaultCmd}):\n> `);
  
  const finalCmd = cmd.trim() || defaultCmd;
  const config = { command: finalCmd };
  
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));
  console.log('✅ Configuration updated!');

  const overwrite = await question('\nDo you want to overwrite backend/src/prisma-playground.ts with the SAFE diagnostic script? (y/N): ');
  if (overwrite.toLowerCase() === 'y') {
    fs.writeFileSync(PLAYGROUND_FILE, SAFE_PLAYGROUND_CODE);
    console.log('✅ Safe prisma-playground.ts generated/updated! You are protected from accidental destructive code.');
  }
  
  rl.close();
}

async function main() {
  console.log('\n=========================================');
  console.log('🛠️  PRISMA PLAYGROUND MANAGER (Root Level)');
  console.log('=========================================');
  
  await ensureConfig();
  
  console.log('\n1. Run Prisma Playground (Diagnostics)');
  console.log('2. Configure / Settings');
  console.log('3. Exit');
  
  const choice = await question('\nSelect an option (1-3): ');
  
  switch (choice.trim()) {
    case '1':
      await runPlayground();
      break;
    case '2':
      await configure();
      break;
    case '3':
      console.log('👋 Exiting...');
      rl.close();
      break;
    default:
      console.log('❌ Invalid option. Exiting.');
      rl.close();
  }
}

main();