// ⚠️ SAFE DIAGNOSTIC SCRIPT
// This file is auto-generated by the root-level playground-cli.js to prevent accidental destructive database operations.
import { PrismaClient } from './generated/prisma';

const prisma = new PrismaClient();

async function runDiagnostics() {
  console.log('\n🔍 =========================================');
  console.log('🔍 RUNNING SAFE DATABASE DIAGNOSTICS...');
  console.log('🔍 =========================================\n');

  try {
    const roles = await prisma.role.findMany({ include: { _count: { select: { rolePermissions: true } } } });
    console.log(`👑 ROLES FOUND: ${roles.length}`);
    roles.forEach(r => console.log(`   - ${r.roleName} (ID: ${r.roleId}, Permissions: ${r._count.rolePermissions})`));

    const properties = await prisma.property.findMany({ select: { propertyId: true, propertyName: true, subscriptionStatus: true, subscriptionEndsAt: true, trialEndsAt: true } });
    console.log(`\n🏨 PROPERTIES FOUND: ${properties.length}`);
    properties.forEach(p => {
      const endDate = p.subscriptionEndsAt || p.trialEndsAt || 'N/A';
      console.log(`   - [${p.propertyId}] ${p.propertyName} | Status: ${p.subscriptionStatus} | Ends: ${endDate}`);
    });

    const users = await prisma.user.findMany({ include: { role: { select: { roleName: true } }, property: { select: { propertyName: true } } } });
    console.log(`\n👤 USERS FOUND: ${users.length}`);
    users.forEach(u => console.log(`   - ${u.fullName} (${u.username}) | Role: ${u.role?.roleName} | Hotel: ${u.property?.propertyName}`));

    const roomTypes = await prisma.roomType.findMany({ include: { amenities: { include: { amenity: true } } } });
    console.log(`\n🛏️  ROOM TYPES FOUND: ${roomTypes.length}`);
    roomTypes.forEach(rt => {
      const amenityNames = rt.amenities.map(a => a.amenity.name).join(', ') || 'None';
      console.log(`   - [${rt.roomTypeId}] ${rt.typeName} (GH₵${rt.basePrice}) | Amenities: [${amenityNames}]`);
    });

  } catch (error: any) {
    console.error('❌ DATABASE ERROR:', error.message);
  } finally {
    await prisma.$disconnect();
    console.log('\n🔍 =========================================');
    console.log('🔍 DIAGNOSTICS COMPLETE. Copy the output above!');
    console.log('🔍 =========================================\n');
  }
}

runDiagnostics();
